### ISSUE TITLE
Request: Max Altitude setting for other cave types

### ISSUE THREAD

**Issue by Circine** [yungnickyoung/Better-Caves#1]
Like the lava caverns have. Or a global value for all caves.
Biomes that are especially steep - in my case Realistic Terrain Generation's Crag, Overgrown Cliffs, and Rainforest - get too many cave openings on the surface even with much higher cutoff depths. Plus, if I raise to 30 or so that has the side-effect of reducing cave height even at lower altitudes.

**Comment by yungnickyoung** [comment]
Good idea! Can't believe I didn't think of this lol. I'll include this in a future release. Will close this issue when the fix is released.

**Comment by yungnickyoung** [comment]
Hey Circine, my apologies for the wait. This has been added in v1.0.3.1, available on CurseForge. I think it should be exactly what you're looking for.
I'll be closing this issue but feel free to message me, either here or on CF, to let me know how it works for you!
