### ISSUE TITLE
Server Requires Clients to Have Mod Installed

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Better-Caves#10]
I would like to be able to run Better Caves on a Vanilla-compatible server. Ideally clients could play on the server without installing Better Caves or Forge. Right now clients can only join a Better Caves server if they have both installed.
Worley's Caves supports vanilla clients, so I'm wondering whether Better Caves could do that too.

**Comment by yungnickyoung** [comment]
Hey, thanks for the suggestion. I actually didn't know that was possible! If Worley's has it, I imagine I can just take a look at their code and mimic what they do - it probably isn't a big change. I'll try to have this out in the next release.

**Comment by yungnickyoung** [comment]
Added in 1.12.2-1.5.1
