### ISSUE TITLE
Caves and Caverns cutting into other structures.

### ISSUE THREAD

**Issue by Runburner** [yungnickyoung/Better-Caves#107]
I am encountering this issue on version BetterCaves-Forge-1.16.4-1.1.1.jar
I am using Forge 35.1.37

Essentially the caves are cutting away at underground structures like Quark Bigger Dungeons and Dungeon crawl dungeons. Thankfully, Dungeon Crawl had a solid structure option which prevented the caves from ruining the dungeons. However, Quark doesn't have anything like that. 

I have used the Better caves on 1.12.2 and didn't really see this be an issue all that much with Roguelike Dungeons or the Quark dungeons. Is there a setting or something that can be set in better caves so that it can avoid cutting away other mods' structures?

**Comment by Runburner** [comment]
Adding to this because I just found out. It's also cutting out your Bettermineshafts mod. Looks to be specifically the flat caverns I believe that are doing this? Here's a screenshot for a visual example.

https://i.imgur.com/oIForGq.png

**Comment by Lughbaloo** [comment]
This is a Quark cave feature you're looking at, not Better Caves.

**Comment by Runburner** [comment]
Wait, is it the crevices module that's doing this then? I wouldn't think that it would interfere with its own world gen.

**Comment by TelepathicGrunt** [comment]
Quark's caves are features iirc. So they could cause floating stuff or eat away at too much like what is shown

**Comment by Runburner** [comment]
I'm going to disable crevices and to a test world gen real quick then.

**Comment by Runburner** [comment]
@TelepathicGrunt @Lughbaloo You were correct, thank you for pointing that out. It was the Crevices module on Quark. I didn't expect it to cut things out like that so I kinda thought it was BetterCaves. It's all good now. Going to close this issue in that case.
