### ISSUE TITLE
There is no sound

### ISSUE THREAD

**Issue by Capsfam** [yungnickyoung/Better-Caves#110]
I start the game up and there is no sound at all, I'm not using any sound mods either. I've removed every mod one at a time to figure out which had the problem and for some reason, it was yours. I just thought I'd let you know I really enjoy using your mod and been using it for a while now this problem only came up now, the version of the game I'm using is 1.12.2 and the mod itself is 1.12.2 - 2.0.4 if it matters.

**Comment by yungnickyoung** [comment]
It is 100% not caused by Better Caves - the mod is entirely server-side. Best of luck in figuring it out.
