### ISSUE TITLE
Error on Worldcreation

### ISSUE THREAD

**Issue by GoldenGamerLP** [yungnickyoung/Better-Caves#111]
Every time i wanna create a new world, this happens:
https://paste.helpch.at/yojucucotu.cs

**Comment by Pepperoni-Jabroni** [comment]
Also failing to create new world in 1.16.5
Log: https://pastebin.com/CSshwP53

**Comment by yungnickyoung** [comment]
> Also failing to create new world in 1.16.5
> Log: https://pastebin.com/CSshwP53

This looks like a crash with Better Mineshafts, not Better Caves. Please make an issue report on the Better Mineshafts tracker.

**Comment by yungnickyoung** [comment]
@GoldenGamerLP Please pastebin the complete latest.log and crashlog.

**Comment by yungnickyoung** [comment]
This issue will no longer happen, since all 1.16 Forge AND Fabric have now received refactors as part of v1.1. Please create a new issue report with more details if you continue to experience crashes.
