### ISSUE TITLE
Confliction

### ISSUE THREAD

**Issue by mysticetus09** [yungnickyoung/Better-Caves#112]
It might be bug or maybe not, but is there a way for YUNGs Better Caves to not overlay the Crawl Dungeon mod?

**Comment by hjpoe** [comment]
I ran into what I believe OP is talking about as well. 

I'm using Minecraft version 1.15.2, with latest versions of Yung's Caves and Dungeon Crawl, and Forge version 31.2.48. I also am using  Terraforged's realistic world type, I'm not sure if this has anything to do with it (also latest version). I have other mods as well in this pack, but the only other one that I think could be related would be Quark, which does spawn some caves (also latest version).

I found one of Dungeon Crawl's structures, and it was filled with the stone types, dirt, clay, etc. that would have been there had the structure not been there.

**Comment by yungnickyoung** [comment]
If you could provide pictures, that would be great. But carvers run before structures generate, so the onus is really on the structure to generate properly and account for the surrounding terrain.

**Comment by hjpoe** [comment]
😅 I already mined all the stuff out of the one I found, but I'll go into a different world (the one I found it in was Hardcore) and see what I can find for you. 

Let me know if you think I should file an issue with Dungeon Crawl.

**Comment by hjpoe** [comment]
I have an update. This structure isn't from Dungeon Crawl. I think it is from the Ruins mod. 

Here are some screenshots: 
![2021-02-11_18 21 03](https://user-images.githubusercontent.com/35583004/107725785-05602700-6cb5-11eb-8907-77545071f8df.png)
![2021-02-11_18 20 17](https://user-images.githubusercontent.com/35583004/107725802-0db86200-6cb5-11eb-892d-0668d9de0dbd.png)
![2021-02-11_16 51 24](https://user-images.githubusercontent.com/35583004/107725808-101abc00-6cb5-11eb-8523-65ad0365bad3.png)
![2021-02-11_16 51 48](https://user-images.githubusercontent.com/35583004/107725812-1315ac80-6cb5-11eb-841f-e4b97ef973a1.png)
![2021-02-11_16 51 40](https://user-images.githubusercontent.com/35583004/107725813-14df7000-6cb5-11eb-86f2-1ee120689c0d.png)
![2021-02-11_16 52 00](https://user-images.githubusercontent.com/35583004/107725816-1741ca00-6cb5-11eb-9cee-edb89f52205a.png)
![2021-02-11_23 18 34](https://user-images.githubusercontent.com/35583004/107729725-a3f18580-6cbf-11eb-930e-68e8d450c635.png)
![2021-02-11_23 18 49](https://user-images.githubusercontent.com/35583004/107729729-a6ec7600-6cbf-11eb-92cf-887bb9a4d44f.png)
![2021-02-11_23 19 30](https://user-images.githubusercontent.com/35583004/107729740-aeac1a80-6cbf-11eb-92ab-cfecb5332fc5.png)

**Comment by yungnickyoung** [comment]
I don't understand, what's the issue here?

**Comment by hjpoe** [comment]
Probably not an issue with your mod, but you said you wanted to see some screenshots.

**Comment by yungnickyoung** [comment]
@mysticetus09 If your issue is the dungeon getting torn up by caves, please check the mod's config. It likely has an option to prevent that from happening.
