### ISSUE TITLE
[Fabric 1.16] Chunk errors along the Z axis and are dependant on the view distance of the server

### ISSUE THREAD

**Issue by MrFireSword** [yungnickyoung/Better-Caves#113]
![image](https://user-images.githubusercontent.com/62079225/108697509-63de9e00-751c-11eb-9b89-3238e7d4dc15.png)

Hello, 
I've noticed a consistent number of chuck errors where vanilla chunks spawn in and they happen from east to west
the distance between those errors depends on the server view distance, I've tested this with View distance 8 and 10 both distance between chunks were 8 a and 10 respectively. 

the image should give some perspective, the chuck error spans the whole way and is consistent on the Z axis. 

Thank you for looking into it. 
Thank you also for this awesome mod :)

-Fires

**Comment by yungnickyoung** [comment]
Fixed in v1.1.
