### ISSUE TITLE
Better Caves forcing generation into Good Night Sleep dimensions causing crashes

### ISSUE THREAD

**Issue by VallenFrostweaver** [yungnickyoung/Better-Caves#115]
Minecraft 1.16.5
Forge 30.0.40
Better Caves 1.1.1
Better Caves config: set to only work in Overworld and not set to global.

When going to Good Night's Sleep dimension (see mod [here](https://www.curseforge.com/minecraft/mc-mods/good-nights-sleep)) the game crashes on server and in single player and the player data must be changed to another dimension to even rejoin the world. Looking at the crash reports it would seem that the caves are still trying to inject into the Good Nights Sleep dimension(s). If this is not a Better Caves thing and is a GNS error instead, please let me know and I'll post a bug report with them. Thank you.

[Crash report](https://pastebin.com/w6WeN88Y)

**Comment by yungnickyoung** [comment]
Even in dimensions where BC is not enabled, it will still be used to call the default cave carvers. In the crash report you can see it is calling the method `useDefaultCarvers`, which is intended behavior.

Based on where it's crashing, it looks like it might be one of the following problems:
1. The world passed in is null
2. `World#getNoiseBiome` is returning null
3. `Biome#getRegistryName` is returning null, meaning they haven't properly registered their biome

The first two issues would be kind of weird, although possible if they are using a custom chunk generator. Number 3 is probably the most likely culprit.

I would make an issue with the Good Night's Sleep team and link them this comment. It seems likely it's an issue on their end.

**Comment by VallenFrostweaver** [comment]
Good Night's Sleep mod has updated at their end to correct the issue. Thank you. <3
