### ISSUE TITLE
Ability to change ore spawn rates in config / Option to reduce rates of ores exposed to air

### ISSUE THREAD

**Issue by Lucipo** [yungnickyoung/Better-Caves#116]
Just like in the new caves, bigger means you get around 20-30 diamonds per mining trip on average without fortune. It's insane. An option to turn/off a config to reduce exposed ore or just change rates of ores individually in config would be great for server-owners that want to keep it vanilla or slow progression or encourage strip mining for ores and caving for dungeons and fighting.

**Comment by yungnickyoung** [comment]
This is outside the scope of this mod. There are plenty of mods offering control over ore spawns already.

**Comment by Lucipo** [comment]
Can I get a name (for fabric) because I couldnt find any.

**Comment by yungnickyoung** [comment]
Not sure about Fabric, but at the very least you can modify the ore spawn rates yourself via datapack.
