### ISSUE TITLE
Crash when launching Server

### ISSUE THREAD

**Issue by ValkyrieofNight** [yungnickyoung/Better-Caves#12]
When trying to launch a server with this mod it causes a crash.

Forge: 28.1.47
MC: 1.14.4

https://pastebin.com/zPJAcnvu

**Comment by yungnickyoung** [comment]
Thanks for this Valkyrie.
A little googling tells me that this dependency is not available in OpenJDK.
I'll be fixing this as soon as possible - in the meantime, please try using Oracle JDK instead as a workaround. Let me know how it goes for you!
