### ISSUE TITLE
Possibility of geolosys ores getting deleted during caves generation

### ISSUE THREAD

**Issue by FenixR** [yungnickyoung/Better-Caves#124]
LIke title says, i have seen a few geolosys veins (and not the one that are random but those close together) that have only a few ores instead of the intended configured amount, probably because this mod deletes them when making the caves.

A recommended solution would be to place a blacklist for blocks/mods that are not deleted or move around during worldgen like these ores.

**Comment by yungnickyoung** [comment]
Caves are placed before ores are generated. I highly doubt this is happening. I would ask the geolosys devs about it.
