### ISSUE TITLE
Can you make the small mineshafts that branch off have support beams too?

### ISSUE THREAD

**Issue by QPCrummer** [yungnickyoung/Better-Caves#126]
I don't really like the way that these float :p 
Just adding the support beams like you do with the big main mineshaft would be awesome
![2021-05-29_15 07 02](https://user-images.githubusercontent.com/66036033/120082233-ca310a80-c08f-11eb-952c-7294a3e71313.png)

**Comment by yungnickyoung** [comment]
This is the wrong GitHub repo lol, but I went ahead and recreated your issue here: https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues/58
