### ISSUE TITLE
crash saying: Could not find required mod: bettercaves requires {yungsapi @ [>=1.16.5-Fabric-5]}

### ISSUE THREAD

**Issue by SuperDingMC** [yungnickyoung/Better-Caves#130]
this happens everytime i try to open the game, please help

**Comment by ClosedTheDor** [comment]
you need to install the new version of yungs api and delete the older version

you can install here [https://www.curseforge.com/minecraft/mc-mods/yungs-api-fabric/files](url)
ande make sure that you downoald the v5
