### ISSUE TITLE
[Fabric Crash] CarverFeature Missing Implementation / Definition

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Better-Caves#131]
Crash occurs upon attempting to enter a world. [Here's my crash report!](https://gist.github.com/Brittank88/5f843b59ddd47665797d4b03de6d10a4)

**Comment by yungnickyoung** [comment]
You are using the snapshot version of Better Caves with 1.17, which doesn't work. There is no Better Caves for 1.17.
