### ISSUE TITLE
Server crash 1.17

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Better-Caves#134]
Fabric loader 0.7.4
Fabric api 0.36.0
YungsApi 1.17 fabric 11
BetterCaves fabric 20w45a-0.1.4

[crash-2021-07-01_11.09.24-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/6749819/crash-2021-07-01_11.09.24-server.txt)

**Comment by yungnickyoung** [comment]
There is no Better Caves for 1.17

**Comment by ghost** [comment]
> There is no Better Caves for 1.17

Ok sorry my bad
