### ISSUE TITLE
Better Caves mod server issues

### ISSUE THREAD

**Issue by Hellishworld** [yungnickyoung/Better-Caves#137]
Hi i'm currently running a 1.12.2 forge server with this mod installed. Suddenly the server starting lagging and i noticed its after this is in the logs

Server thread/INFO [bettercaves]: Better Caves config file for dimension 0 not found. Using global config...
08.09 21:47:27 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:lava' as lava in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:27 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:water' as water in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:27 [Server] Server thread/INFO [bettercaves]: Better Caves config file for dimension 0 not found. Using global config...
08.09 21:47:27 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:lava' as lava in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:27 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:water' as water in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Better Caves config file for dimension 0 not found. Using global config...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:lava' as lava in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:water' as water in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Better Caves config file for dimension 0 not found. Using global config...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:lava' as lava in cave generation for dimension 0 (OVERWORLD) ...
08.09 21:47:28 [Server] Server thread/INFO [bettercaves]: Using block 'minecraft:water' as water in cave generation for dimension 0 (OVERWORLD) ...

Not sure if it is causing the lag but since after every new chunk that is loaded now seems to lag out the server really bad

**Comment by yungnickyoung** [comment]
This output is normal and intended. It doesn't cause any lag.
