### ISSUE TITLE
1.17.1 Game Crashes

### ISSUE THREAD

**Issue by Ahelotech** [yungnickyoung/Better-Caves#140]
The Better Caves causes 1.17.1 to crash with Exit Code: 0.

**Comment by CorgiTaco** [comment]
You've sent no logs. Send those

**Comment by Ahelotech** [comment]
[fail log.txt](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/7161447/fail.log.txt)

**Comment by poombus** [comment]
If I'm not mistaken, this mod doesn't have a 1.17 version yet?

**Comment by yungnickyoung** [comment]
Correct, there is no Better Caves for 1.17.
