### ISSUE TITLE
Further Features Request

### ISSUE THREAD

**Issue by ProfessionaFiddler** [yungnickyoung/Better-Caves#141]
I have noticed some things, and have some suggestions as following:

- Surface caves are always separated. Rarely do they cross with other cave types. Maybe make them **always** connect to a, say cave type 2? Regarding cave type 1:
- Type 1 Caves feel very much like vanilla. I think it will be much more interesting, if they woul be just smaller. Like in real life you see those incredibly low caves where you have to crawl? So shrinking type 1 down to tunnels is my idea here.

And lastly, a super new idea - enhanced ravines. In minecraft they are always just a horizontal crack in the ground. What if you would make them triangular? Small cut on the surface, big expanding ravine inside? Maybe even a bit rounded? Ravine exposure, horizontal shape, vertical shape - all these things can be reworked.

I just felt like sharing my experience and ideas here. What you want to do with it, is of course up to you.
If you want to give it a thought, please keep in mind that 1.17+ is still very young, mod-poor version. Despite all the new generation code, they obviously have a long way to go compared to you. 1.16 is still popular for modding, so I would stick with it for half a year at least.

There is just geniunly that tripple mod combo - "your Better Everything + Subterranian Wilderness + Terraforged", which outclasses 1.17 in every aspect.

**Comment by yungnickyoung** [comment]
Good feedback, but Better Caves is basically a finished project at this point. It won't be receiving any major changes.
