### ISSUE TITLE
i only have creatures from aquaculture 2 spawning in your water caves?

### ISSUE THREAD

**Issue by Mr-Syntax** [yungnickyoung/Better-Caves#142]
if i want to add other creatures to the spawn list there, is that on their end?
i would really like to add a couple of hostile creatures in the waters

great mod btw that cave diving is just amazing

used your mod in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by yungnickyoung** [comment]
Mob spawning isn't touched by Better Caves. In general, if a mod adds mobs, then that mod will be defining when/where the mob spawns.

Sorry for the late response btw. If you have any questions, feel free to ask on [Discord](discord.gg/rns3beq), where you'll get a response way quicker lol
