### ISSUE TITLE
Compability with Orcinus caves

### ISSUE THREAD

**Issue by Mr-Syntax** [yungnickyoung/Better-Caves#143]
so i have both your mod installed and orcinus and its almost working perfect except it generates these kinds of caves once in a while

![image](https://user-images.githubusercontent.com/59544236/137062945-1f990dd4-8012-42ad-8703-4e088e45e31b.png)

**Comment by Mr-Syntax** [comment]
![image](https://user-images.githubusercontent.com/59544236/137063055-498699f6-4bb3-4226-b853-ed3406ad9609.png)

its in this pack

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Mr-Syntax** [comment]
i really like the combination of your mods together it would look epic of this issue was fixed
![2021-10-18_01 55 48](https://user-images.githubusercontent.com/59544236/137651394-49571384-f3c8-4340-9a0b-f503bfad7d51.png)

its like its just carving these sharp slices out that make no sense :-/

**Comment by yungnickyoung** [comment]
These look like Quark crevices, no?

**Comment by Mr-Syntax** [comment]
omfg your totally right thanks for telling me that :D it fixed it...

i just updated your API and started having this problem tho??

![image](https://user-images.githubusercontent.com/59544236/137723460-22f1165b-234f-4a9d-a9e6-45927e6c7d01.png)

its directly under the structures from the Shrines pack

**Comment by Mr-Syntax** [comment]
shit okay thats not on you its something else sorry for disturbing

**Comment by Mr-Syntax** [comment]
it was shrines rolling itself back....
