### ISSUE TITLE
Fabric 1.17 when?

### ISSUE THREAD

**Issue by kingarthur0975** [yungnickyoung/Better-Caves#146]
Not an issue with the mod itself, but if the mod is getting an update to 1.17, is there any info on when? I have a 1.17 modpack that would really benefit from this mod.

**Comment by yungnickyoung** [comment]
Sorry, Better Caves won't be ported to versions after 1.16. There isn't much of a need for it with 1.18 coming out soon.

**Comment by kingarthur0975** [comment]
Aww man.... alright.
