### ISSUE TITLE
Server hangged after carved took too much to generate

### ISSUE THREAD

**Issue by FelipeCardona95** [yungnickyoung/Better-Caves#148]
Hello so I been having some issues with the carver structure in my server since I have my max tiick timee set to 60000 this time the server automatically crashed cause it took more than that time, this is the server log before crashing
![image](https://user-images.githubusercontent.com/11274437/147789793-82d9d676-08fa-46ee-9cef-f6bbb499ae95.png)
the server hangs after the carver structure gets generated and any other structure after it start lagging as well
here is the crash log 
https://pastebin.com/tPNbrd6t
let me know if you find anything else,
as a side note this is not a TerraForeged issue since its just telling this specific structure was too slow to generate
https://github.com/VazkiiMods/Quark/issues/2850

**Comment by yungnickyoung** [comment]
I don't see anything suggesting the problem is Better Caves. It's more likely to be another modded structure. It's pretty common for structure mods to cause these kinds of crashes. 

Does it crash every time, or only this once?
