### ISSUE TITLE
Error while loading mods

### ISSUE THREAD

**Issue by R4D0CZE** [yungnickyoung/Better-Caves#149]
Anyone know how to fix this
![Snímek obrazovky 2022-01-02 031258](https://user-images.githubusercontent.com/67956230/147864238-69307a5c-fedd-4a5c-a76e-0677336bc162.png)
?

**Comment by yungnickyoung** [comment]
These mods have other mods they depend on to load. So you'll need to download the mods it says - YUNG's API, iChunUtil, and GeckoLib.
