### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by Frazack333** [yungnickyoung/Better-Caves#153]
Hello, wanted to let you know this mod completely changed my playstyle, spelunking is finally viable again, no need for massive ladder projects to get to bedrock, no need for strip mining, tons of opportunities for danger and loot and all you have to do is find an opening somewhere, this mod alone can make you feel progression by just how deep you managed to delve and come back alive, amazing work. no issues, no requests, just thank you deeply (you can close this of course)

**Comment by yungnickyoung** [comment]
I'm glad you like it so much :) feel free to join the [discord](http://discord.gg/yung) if you wanna stay updated on my other mods!
