### ISSUE TITLE
Seemingly stalling error

### ISSUE THREAD

**Issue by erragar** [yungnickyoung/Better-Caves#18]
So this is an odd one, and I don't know what file to include to show it, but I've created two modpacks with this Mod and a number of other mods that makes minecraft literally just... stall. I can move and see things, but chunks don't update, the internal server stalls and attempting to save and leave the game leads to nothing but the "saving game" screen for, I've left it going for over 8 hours. I'm running this on a 1.14.4 Modpack.

I'll include my list of mods, as, again, I don't know what file to even show you and as an experiment, I removed this mod and "Expanded Caves" from the other pack and it's working smoothly.

A Lib	al132	alib-1.14.4-7.jar	

Advanced Mining Dimension	henkelmax	mining_dimension-1.14.4-1.0.7.jar	
Advanced Rotten Flesh to Leather	ThatAlexanderA	Forge_RFTLBPlus1.4.4.jar	
Advanced Shulkerboxes	henkelmax	shulkerbox-1.7.0.jar	
Alchemistry	al132	alchemistry-1.14.4-7.jar	
Basic Nether Ores	cScotPlay	BasicNetherOres-1.14.4-3.2.2.jar	
Better Animal Models	cybercat5555	betteranimals-1.14.4-5.2.1.jar	
Better Animals Plus	cybercat5555	betteranimalsplus-1.14.4-7.1.2.jar	
Better Signs	Angercraft	BetterSigns-1.0_v1.14.4.jar	
Block Drops (JEI Addon)	KidsDontPlay	blockdrops-1.14.4-1.0.2.jar	
BountifulBaubles	Cursed1nferno	bountifulbaubles-1.14.4-0.0.1.jar	
Bunch Of Biomes!	Lemonszz	bunchofbiomes-1.14.2-1.0.3.jar	
Carry On	Tschipp	CarryOn MC1.14.4 v1.12.4.jar	
Chem Lib	al132	chemlib-1.14.4-10.jar	
Common Capabilities	kroeser	CommonCapabilities-1.14.4-2.4.4.jar	
Controlling	Jaredlll08	Controlling-5.0.4.jar	
Corail Tombstone	Corail_31	tombstone-4.1.5-1.14.4.jar	
Corail Woodcutter	Corail_31	corail_woodcutter-1.0.6-1.14.4.jar	
Crafting Station	tfarecnim	craftingstation-2.0.6.jar	
Crafting Tweaks	BlayTheNinth	CraftingTweaks_1.14.4-10.1.4.jar	
Create	simibubi	create-mc1.14.4_v0.1.1.jar	
CTD Core	TheMasterGeneral	CTD-Core-1.14.4-2.0.5b.jar	
Curios API	TheIllusiveC4	curios-FORGE-1.14.4-1.0.3.jar	
Cursed Earth	tfarecnim	cursedearth-1.3a.jar	
Cyclops Core	kroeser	CyclopsCore-1.14.4-1.5.5.jar	
Extended Caves	polyvalord	extcaves-1.3.2.jar	
Extended Lights	polyvalord	extlights-1.6.jar	
Extra Anvils	tfarecnim	extraanvils-2.4.jar	
Extra Boats	TheMarkus1002	extraboats-1.1.2-1.14.4.jar	
Fast Leaf Decay	olafskiii	FastLeafDecay-v17.jar	
Glassential	Lykrast	glassential-forge-1.14.4-1.1.1.jar	
Glowglass	TyFrostbyte	Glowglass-1.14.4-1.1.jar	
Humbling Bundle	Serilum	hb_1.14.4-1.1.jar	
Inventory Sorter	cpw	inventorysorter-1.14.4-16.2.0.jar	
Iron Chests	ProgWML6	ironchest-1.14.4-9.1.5.jar	
Iron Shulker Boxes	ProgWML6	ironshulkerboxes-1.14.4-3.1.12.jar	
Just Enough Items (JEI)	mezz	jei-1.14.4-6.0.0.18.jar	
Ma Essentials	Statywek	maessentials-1.0.10.jar	
MCAdditions	OneRealKieran	MCAdditions-1.2.0.jar	
MCFurnace	maatfx	MCFurnace-1.14.4-DEV-1.3.2.jar	
McJtyLib	McJty	mcjtylib-1.14-3.5.8-alpha.jar	
Metal Barrels	tfarecnim	metalbarrels-1.3d.jar	
Mine and Slash	mcrobertx22	Mine and Slash-1.14.4-2.9.2.jar	
Mo' Glowstone	TheMasterGeneral	Mo-Glowstone-1.14.4-2.0.4.jar	
Modpack Configuration Checker	matt1235r	Modpack Configuration Checker-1.14.x-v1.7.1.jar	
More Ores In ONE	KG20	MoreOresInONE-1.5.jar	
Mouse Tweaks	YaLTeR	MouseTweaks-2.12-mc1.14.4.jar	
Nametags Without Anvils	tfarecnim	nametagswithoutanvil-1.1.jar	
Ore Excavation	Funwayguy	OreExcavation-1.6.141.jar	
Placebo	Shadows_of_Fire	Placebo-1.14.4-2.3.1.jar	
PlantTech 2	chrisland	planttech2-0.01.04.jar	
Prefab	wuestman	prefab-1.4.0.7.jar	
Pyramid Plunder	laton95	PyramidPlunder-1.14.4-1.1.jar	
Reap Mod	henkelmax	reap-1.10.2.jar	
Refined Relocation 2	BlayTheNinth	RefinedRelocation_1.14.4-6.2.4.jar	
SecretRoomsMod	AbrarSyed	secretrooms-6.0.4.jar	
Shulker Drops Two	Serilum	shulkerdt_1.14-1.1.jar	
Silent Lib	SilentChaos512	SilentLib-1.14.4-4.4.0+44.jar	
Silent's Gems	SilentChaos512	SilentGems-1.14.4-3.4.6+79.jar	
Silent's Mechanisms	SilentChaos512	SilentMechanisms-1.14.4-0.6.6+39.jar	
The Endergetic Expansion	endergized	The-Endergetic-Expansion-1.14.4-v1.0.jar	
The Farlanders	ModdingLegacy	farlanders-1.14.4-1.1.0.jar	
Thermal Solars	JoltEffect	thermalsolars-1.14.4-0.1.jar	
Toast Control	Shadows_of_Fire	ToastControl-1.14.4-2.2.0.jar	
Tool Belt	gigaherz	ToolBelt-1.14.4-1.12.3.jar	
Turf	Lykrast	turf-1.14.4-1.0.0.jar	
U Team Core	HyCraftHD	u_team_core-1.14.4-2.7.4.134.jar	
Upgrade Aquatic	minecraftabnormals	Upgrade Aquatic Wave Three v6 - Beta 1.0.8.jar	
Useful Backpacks	HyCraftHD	useful_backpacks-1.14.4-1.7.1.41.jar	
VoxelMap	MamiyaOtaru	forgemod_VoxelMap-1.9.13b_for_1.14.4.jar	
YUNG's Better Caves	YUNGNICKYOUNG	BetterCaves-1.14.4-1.0.1.jar

**Comment by yungnickyoung** [comment]
Thanks for the report. Please be more specific as to when and how this error occurs. 
Is it upon startup, or after keeping the server running for a while? 
When you say chunks don't update, do you mean that attempting to break blocks, update light levels etc. has no effect? 
Has this behavior been seen when the mod is used on its own, or only in a modpack? 
Does this occur when running locally, on a dedicated server. or both?

Apologies for all the questions, but this seems like a tricky one. Please be as specific as possible. Thanks!

**Comment by erragar** [comment]
The stalling occurs, normally after a few minutes to about an hour of play. I'll be going a long just fine, and then, my mining yields no results, no chest opens, no mob moves, no door opens, the game has stalled with no error message or shutdown. Attempting  to save and return to the title screen results in an equally stalled title screen. Unfortunately that is as specific as I can get, This is a single player world, that I've been testing for modpack building. I have not used your mod on it's own however.

**Comment by yungnickyoung** [comment]
Gotcha, I'll take a look at this. Does your world end up saving fine? Or does the save end up corrupted/unusable?

**Comment by erragar** [comment]
I normally have to use Task Manager to close Minecraft when this happens, and it usually back tracks me up to about 5 minutes of game play into the past (Or about the last autosave)

**Comment by yungnickyoung** [comment]
Was never able to recreate this one. Going to close it since basically the entire 1.14 codebase has been rewritten since this was made.
