### ISSUE TITLE
Feature Request: Better Cave Surface Openings

### ISSUE THREAD

**Issue by CalaMariGold** [yungnickyoung/Better-Caves#26]
I'd like to suggest an entirely new cave region, used to make better openings.

Currently, if you set the cutoff depth to anything less than 4, you get really weird openings. Entire hills are carved off and it generally looks really bad.

I feel like the mod needs openings similar to vanilla cave openings; ditches that lead to caves.

Try it out yourself by putting the cutoff depth to like 1 or 2.

**Comment by yungnickyoung** [comment]
I agree that caves need better openings, but I'm not sure how to go about it at this time. My caves dont generate the same way as vanilla, so creating openings like that isnt as straightforward. That being said, I'll try to come up with a new way to get some better openings for ya.

Also, if setting cave surface cutoff low looks really bad - just dont do it lol

**Comment by yungnickyoung** [comment]
One idea: create a layer of vanilla-esque Perlin worms near the surface, and prevent type 1 and 2 caves from spawning that high up.  These vanilla-esque worm-like caves then have a chance of intersecting with the regular caves (although they may not intersect in pretty ways).

**Comment by yungnickyoung** [comment]
Added in 1.12.2-2.0 :)
Will be added in future versions as well, so I'll close the issue.
