### ISSUE TITLE
Caves dig through strongholds

### ISSUE THREAD

**Issue by yungnickyoung** [yungnickyoung/Better-Caves#29]
Consider adding check for stone bricks in canReplaceBlock() to fix this.
Are there any other potential downsides of or gamebreaking issues that may be caused by not carving stone bricks?

**Comment by Benji-Collins** [comment]
Could also exclude mossy cobblestone to protect dungeons.

**Comment by yungnickyoung** [comment]
So after some investigation, it appears that caves don't actually destroy strongholds, at least not directly.

"it is a common myth that caves themselves cut through strongholds when in reality the stronghold generator ignores air when generating walls"
See [this reddit thread](https://www.reddit.com/r/Minecraft/comments/b6d487/stongholds_always_destroyed_by_caves/)

The same logic applies to dungeons - they are not being dug out, but rather they don't replace air blocks with cobble during generation.

The only fix for this would be to modify stronghold code to replace air blocks as well as stone when generating.

**Comment by Benji-Collins** [comment]
Interesting. Thanks for letting me know.

**Comment by yungnickyoung** [comment]
Ended up making a separate mod to address this issue:
https://www.curseforge.com/minecraft/mc-mods/save-my-stronghold

**Comment by Benji-Collins** [comment]
Wow that was fast. I’ll try it out later and see how it goes.
