### ISSUE TITLE
Request: Dimension Setting

### ISSUE THREAD

**Issue by Skyrrel** [yungnickyoung/Better-Caves#3]
Add a dimension setting in config to choose in which dimensions this mod will attempt to generate caves.
I'm currently using this mod with Just Enough Dimension, I've created a new all stone dimension with that mod but Better Caves caves aren't generated there.

**Comment by yungnickyoung** [comment]
Thanks for the idea, Skyrrel. I've added this in a test build 1.0.4.0-dev.
Check it out here:
https://github.com/yungnickyoung/YUNGs-Better-Caves/releases/tag/untagged-c43505333468aa21ba65

Let me know if it works for you, and if so I'll push it to the next official build.

**Comment by Skyrrel** [comment]
The link doesn't work.

**Comment by yungnickyoung** [comment]
Sorry, just check build 1.0.4.0-dev under the releases tab.

**Comment by Skyrrel** [comment]
Thanks, it works very well in my modpack with Superflat Caves to force cave gen in superflat worlds, Just Enough Dimensions to create a superflat dimension and this mod to generate awesome shaped caves. 👍 

I think it makes more sense to make the Dimension Config a whitelist as default to make sure it doesn't conflict with other mods.

**Comment by yungnickyoung** [comment]
Hmm good point. I'll switch it to a whitelist and release it in a couple hours.

**Comment by yungnickyoung** [comment]
Whitelisting is added in 1.4.0 on CurseForge. Should be everything you need, so I'm gonna close this issue. Let me know how it goes for you!
