### ISSUE TITLE
Forced cavern topside closeoff is not sufficient for fully closing off caverns under oceans

### ISSUE THREAD

**Issue by yungnickyoung** [yungnickyoung/Better-Caves#33]

**Comment by BugmanBugman** [comment]
I was going to ask if ask tiny pockets on the ocean floor opening  into caves was vanilla behavior, it happens occasionally in my worlds but not frequently

**Comment by yungnickyoung** [comment]
It should happen very rarely in the most recent versions of both the 1.12 and 1.14 versions of the mod, assuming you're using default config settings dealing with cavern height.

This issue refers to when you set the cavern top to be at an altitude greater than the surface. Say you set it to y=50, but the ocean floor is at y=30. The caverns are supposed to be 50 high where possible, but then force themselves to close off when the surface height is below 50. Currently, the caverns close themselves off, but they do so too slowly, resulting in them breaking into the ocean floor.

Have you changed any settings regarding caverns or surface cutoff? Under default settings, caves and caverns should only penetrate the ocean floors in two kinds of places: 1) places where the ocean floor altitude is less than the default cavern top (y=30) (which shouldn't ever happen), or 2) places where the ocean floor is very mountainous or has a steep drop-off

**Comment by yungnickyoung** [comment]
Commit 4dd16213d9c8b13cc1e6da065aa515c91e9a4f05 attempts to address this. Using default y=30 height for caverns, ocean floor holes are almost entirely nonexistent. The frequency of openings is somewhat mitigated when setting the height far above ocean floor levels (say, y=60). However, there are still many holes when the height is set that high, especially on steep drops. It seems like this may be unavoidable (or at least require a much more elaborate surface check) due to adjacent chunks propogating cascading falling of gravel/sand to adjacent chunks that may have already been safely processed.

**Comment by yungnickyoung** [comment]
This is now fixed in 1.12.2-2.0. In addition, flooded caverns and an option for preventing cascading gravel falling now exist, preventing any problematic generation in the event an ocean cavern doesn't properly close off.
This change will be ported to future versions.
