### ISSUE TITLE
Feature Request: Improved Ravines

### ISSUE THREAD

**Issue by Mad-Gnome** [yungnickyoung/Better-Caves#39]
Your mod is already adjust the caves/caverns awesomely.  What about an additional option for the ravines where the user could configure values for height/length/width of ravines

**Comment by yungnickyoung** [comment]
9556b40 tweaks ravines to use the proper liquid altitude.
No plans for other ravine options at the moment. Will probably add underwater ravines in oceans.

**Comment by yungnickyoung** [comment]
1.12.2-2.0 features the addition of flooded ravines on top of the aforementioned tweak. Future versions will receive this upgrade as well.
Gonna close this request as there are no plans for further changes to ravine gen. I think vanilla does a good job already of varying ravine parameters.
