### ISSUE TITLE
Feature Request: Flooded Underground/config tweak

### ISSUE THREAD

**Issue by Circine** [yungnickyoung/Better-Caves#48]
I'm using a Customized worldgen preset that creates a lot of islands in oceans, and caves that generate through them flood even above sea level. Would it be possible to either detect sea level or just have a general Y-level config option, above which caves won't flood?

https://i.imgur.com/vkoD4gL.png

**Comment by yungnickyoung** [comment]
Ah, my bad. There's not really any terrain like this in normal vanilla gameplay, since the biome always becomes a beach before the surface hits sea level, so I didn't realize this would be an issue.
I'll add a check to only flood below sea level.
