### ISSUE TITLE
Quark Cave Roots generating mid-air

### ISSUE THREAD

**Issue by SlimF** [yungnickyoung/Better-Caves#49]
As the title says, Quark's Cave Roots generate in mid air with Better Caves installed.
This is on 1.15.2
![2020-05-12_08 53 44](https://user-images.githubusercontent.com/6482572/81643463-4d080880-942e-11ea-981a-506b07da9343.png)

**Comment by Matthysse** [comment]
Can agree 
![2020-05-12_09 51 31](https://user-images.githubusercontent.com/32510957/81664864-3cf92480-9440-11ea-91bd-5afd17108cdb.png)

**Comment by Matthysse** [comment]
And decorations on the terrain are not removed (flowers, grass) on top caverns entrances.

**Comment by yungnickyoung** [comment]
Thanks for the info guys.

Looks like this only happens along chunk boundaries. The roots check for adjacent stone blocks to place themselves on; however, they also do this along chunk boundaries, so if the adjacent chunk hasn't been processed yet, they will be placed against it. The adjacent chunk is then carved, leaving floating roots. I'll be talking to the Quark devs about this.

@Matthysse can you make a separate issue report regarding the flowers and grass? I think it may be separate.

**Comment by yungnickyoung** [comment]
Looks like Vazkii already made the change. No word on when the next update will come, though.
You can see the issue I made over on Quark here: https://github.com/Vazkii/Quark/issues/2144

**Comment by ArMoReDfUrY** [comment]
Neat.   

;P

**Comment by ArMoReDfUrY** [comment]
And it's released. 
Quark-r2.1-236.jar

**Comment by yungnickyoung** [comment]
Well that was quick

**Comment by ArMoReDfUrY** [comment]
Wastes no time ...

**Comment by yungnickyoung** [comment]
Appears to be fixed.
