### ISSUE TITLE
Better Caves seems to be messing up ocean floor terrain, creating holes in that sort of ruin caves

### ISSUE THREAD

**Issue by BugmanBugman** [yungnickyoung/Better-Caves#5]
![2019-09-27_23 34 09](https://user-images.githubusercontent.com/40730042/65811559-0d7efb80-e180-11e9-86b4-024482d45ee4.png)
![2019-09-27_23 34 14](https://user-images.githubusercontent.com/40730042/65811560-0fe15580-e180-11e9-9fd4-c382bc588501.png)
![2019-09-27_23 34 18](https://user-images.githubusercontent.com/40730042/65811562-11128280-e180-11e9-8030-d0b3fca07e6b.png)
![2019-09-27_23 35 58](https://user-images.githubusercontent.com/40730042/65811565-1243af80-e180-11e9-9c0f-21a766b3af1d.png)

**Comment by yungnickyoung** [comment]
Thanks for the issue report Velocihater. This is definitely unintended - I perform checks for gravel and whatnot to prevent this from happening, so there may be a bug in my code, or some scenario I haven't accounted for. 

I'll be taking a look at this in the future and hopefully fixing it, but it is not a priority to fix this issue at this point. Hopefully this doesn't ruin your caving experience too much.

**Comment by BugmanBugman** [comment]
Seems to still occur in 1.5.0

![2019-10-04_18 10 06](https://user-images.githubusercontent.com/40730042/66249282-58f05700-e6f6-11e9-9070-b8ba21e1aaae.png)
![2019-10-04_18 09 57](https://user-images.githubusercontent.com/40730042/66249283-5d1c7480-e6f6-11e9-993f-974acf25360d.png)
![2019-10-04_18 09 50](https://user-images.githubusercontent.com/40730042/66249285-5f7ece80-e6f6-11e9-87ca-32e172e7257b.png)
![2019-10-04_18 09 44](https://user-images.githubusercontent.com/40730042/66249286-63125580-e6f6-11e9-86a0-4f2f40c67369.png)

**Comment by yungnickyoung** [comment]
Hey Velocihater, this was not addressed in 1.5.0. I'll be leaving a comment on this issue report when the issue has been addressed.

**Comment by yungnickyoung** [comment]
This should be fixed in v1.12.2-1.6.0. 

Added the 1.14.4 tag because it probably needs to be adjusted in that verson as well.

**Comment by yungnickyoung** [comment]
Turns out v1.14.4-1.0.1 already includes water in surface checks.
