### ISSUE TITLE
Decorations not removed on cavern entrances

### ISSUE THREAD

**Issue by Matthysse** [yungnickyoung/Better-Caves#51]
Hello!
You said I should create a new issue for this so here it is :)
So I know the problem of few grasses floating on top of cavern entrance is already in Minecraft, but it updates and there is not that much. But with Biomes O plenty, project vibrant journey, quark and Terraforged, it seems that the decorations do not remove at all, they are always floating as if there was grass under them. Here are a lot of example (this happens with every cavern entrance)
![2020-05-12_22 43 16](https://user-images.githubusercontent.com/32510957/81744058-fbe62c00-94a2-11ea-8f6b-17e4be1ed3b1.png) 
![2020-05-12_22 43 32](https://user-images.githubusercontent.com/32510957/81744059-fc7ec280-94a2-11ea-84ad-5fd3e261b6c6.png)
![2020-05-12_22 43 51](https://user-images.githubusercontent.com/32510957/81744062-fc7ec280-94a2-11ea-9f2b-b079ec560fb2.png)
![2020-05-12_22 42 13](https://user-images.githubusercontent.com/32510957/81744048-fa1c6880-94a2-11ea-9d2a-0cb7e994ede3.png)
![2020-05-12_22 43 06](https://user-images.githubusercontent.com/32510957/81744052-fb4d9580-94a2-11ea-9b5b-e56f150a9bce.png)
![2020-05-12_22 43 06_2](https://user-images.githubusercontent.com/32510957/81744057-fb4d9580-94a2-11ea-8975-fa2ee9c8d802.png)

**Comment by yungnickyoung** [comment]
I have not found a fix for this yet. Now that the carver is implemented as a feature, it seems it is not possible for other features to use the updated heightmap. Hoping for worldgen code changes in future versions of Minecraft so that I'll have the ability to fix problems like this and #56.

**Comment by DamienBrittan** [comment]
no fix so far ? sad .

**Comment by BugmanBugman** [comment]
> no fix so far ? sad .

Can you be please mindful of what you say? These words discourage modders

**Comment by DamienBrittan** [comment]
I'm sorry . I've just said that it's sad , but glad you trying to fix it :c

**Comment by yungnickyoung** [comment]
Fixed with v1.1 in 1.16.4.

1.14 and 1.15 are no longer supported, and will therefore not be receiving this fix.
