### ISSUE TITLE
Feature Request: More options for flooded caves

### ISSUE THREAD

**Issue by Compegen** [yungnickyoung/Better-Caves#57]
I like the flooded caves & don't want to completely disable them, but because it floods all caves in the ocean, it is impossible to cave near/ in the ocean normally.

Possibly add a feature that only makes caves connected to ocean ravines become flooded. 
Alternatively, add a weight for flooded caves, allowing non-flooded caves to spawn in the ocean.

If also possible, when flooded caves are disabled but not flooded ravines, make flooded ravines more sealed so there's not as much overflow into connected caves.

**Comment by yungnickyoung** [comment]
Hey, sorry for the late response. I sympathize a lot with this request, but unfortunately this isn't really possible with my algorithm as is. I would have to somehow change things around quite a bit in order for this to be plausible.
