### ISSUE TITLE
Cave Generation Can 'Overwrite' AE2 Meteors

### ISSUE THREAD

**Issue by ghost** [yungnickyoung/Better-Caves#58]
There isn't any logs to show unfortunately, nothing crashes, it's just that before adding this mod, the world spawn is directly next to an AE2 meteorite. After adding the mod and regenerating the world (same seed), everything is the same except the meteor is gone. The meteorite compass still believes a meteor is in that location though.

I'm playing on `1.12.2`, using `bettercaves-1.12.2-2.0.3` and forge version `14.23.5.2854`. Let me know if you need any more information.

I should add - meteors still spawn in the world. This one was overwritten though, and if it's easily fixable I may as well let you know about it!

**Comment by yungnickyoung** [comment]
Can you provide the world seed?

**Comment by ghost** [comment]
Seed: `tagnartobeanhim` (inside joke :P)
World Type: `DEFAULT` (I'm a dummy and forgot to switch it over to BOP lol)
Modlist: https://hatebin.com/bothdgufny

**Comment by ghost** [comment]
Hello again!

As it turns out, these meteorites might actually be spawning deep underground, as if they somehow believe that a cave's floor is the surface? I'm not sure how else to explain it, here's a photo:
![image](https://user-images.githubusercontent.com/24266948/85128442-a0167c00-b274-11ea-92ab-28bec63dba20.png)
aha wrong photo :'P

**Comment by ghost** [comment]
I think I can confirm that this is happening consistently:
![image](https://user-images.githubusercontent.com/24266948/85128617-ff748c00-b274-11ea-95e6-5b0dbbd2a45f.png)

**Comment by yungnickyoung** [comment]
Seems like poorly made surface detection code on their end, in that case.

**Comment by ghost** [comment]
Is this a fix on their end, or fixable on your end? Would you recommend I post a report on their issue tracker?

**Comment by yungnickyoung** [comment]
Yeah I would do that and see what they have to say

**Comment by yungnickyoung** [comment]
Looks like they are designed to spawn underground as well as on the surface. Seems kinda weird to me, but that is their design decision.

**Comment by ghost** [comment]
Yeah, I agree that it seems like a weird design choice. Sorry for any wasted time - I've just never seen them underground before..

**Comment by yungnickyoung** [comment]
No worries!
