### ISSUE TITLE
Massive Air Bubbles in Oceans

### ISSUE THREAD

**Issue by WenXin20** [yungnickyoung/Better-Caves#60]
`Minecraft v1.15.2`
`Forge v31.2.19`
`Better Caves v1.0`

Massive air bubbles seem to form in oceans, extending underneath the land. I'm using a bop world type, if that affects anything.

![2020-06-17_00 15 33](https://user-images.githubusercontent.com/12000593/84858071-0c546e00-b030-11ea-9100-adca924eae14.png)
![2020-06-17_00 14 54](https://user-images.githubusercontent.com/12000593/84858080-124a4f00-b030-11ea-9779-79cb390e306b.png)

**Comment by yungnickyoung** [comment]
Are you using quark? Looks like one of those sideways ravines to me.

**Comment by WenXin20** [comment]
Yes, Quark is being used. I didn't realize Quark added that. But it seems to extend into the water.

**Comment by yungnickyoung** [comment]
Yeah, it's a feature of theirs and I'm pretty sure that is what this is. I would try posting this on [their issue tracker](https://github.com/Vazkii/Quark/issues) to see if they can help you out.

**Comment by WenXin20** [comment]
Thanks, I'll give it a try.
