### ISSUE TITLE
Caves don't get generated in Chisel basalt

### ISSUE THREAD

**Issue by Gliese-832-c** [yungnickyoung/Better-Caves#61]
Self-explanatory title. I have a custom dimension which uses these blocks as the main block in the world, and there are no caves at all in that region. My suggestion is to add an array of whitelisted blocks that are allowed to be replaced, and possibly a boolean config that turns it into a blacklist so all blocks besides these get replaced.

**Comment by yungnickyoung** [comment]
Can you specify version? And what mod are you using to generate the Chisel blocks as part of the world? By default the caves should carve the top and filler blocks of each biome, no matter what they are.

**Comment by Gliese-832-c** [comment]
I apologize for the late reply.
The version I'm using is 1.12.2-2.0.3.
I use BiomeTweaker to create a custom biome with the Chisel basalt blocks as the main filler block.
