### ISSUE TITLE
Crash server-sided with Afraid Of The Dark

### ISSUE THREAD

**Issue by Zack7292** [yungnickyoung/Better-Caves#62]
basically when you go in a server with this mod and Afraid Of The Dark while generating your  world will randomly overload and the server will crash

crash log: [crash-2020-07-12_13.21.43-server.txt](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/4909426/crash-2020-07-12_13.21.43-server.txt)

other mods used in this precise crash (it's a WIP modpack update): https://www.mediafire.com/file/rhaqz715h4pssuj/InFex_V-Pr%E9-0.0.3d.zip/file

**Comment by yungnickyoung** [comment]
Can you put the crash log in a pastebin?

**Comment by Zack7292** [comment]
No probleme here: https://pastebin.com/Dvr25vAT

**Comment by Zack7292** [comment]
btw i've also open an issue on Afraid of the dark's curse page here: https://www.curseforge.com/minecraft/mc-mods/afraid-of-the-dark/issues/6

**Comment by Zack7292** [comment]
Sorry for disturbing you, this seem to be coming more from Afraid of the dark since my friend removed it to test and it wasn't crashing anymore :)
