### ISSUE TITLE
Way too many fish are spawning in underground flooded caves

### ISSUE THREAD

**Issue by nepphhh** [yungnickyoung/Better-Caves#64]
![2020-07-29_17 52 16](https://user-images.githubusercontent.com/4913409/88857455-4df63e00-d1c4-11ea-9a57-a20e7a07ac94.png)
![2020-07-29_17 47 47](https://user-images.githubusercontent.com/4913409/88857232-e3450280-d1c3-11ea-8e6d-9ae4e84ef7a4.png)
![2020-07-29_17 52 21](https://user-images.githubusercontent.com/4913409/88857461-4fc00180-d1c4-11ea-99a4-15acfaf8462c.png)

All images from the same cavern system, right next to each other & right below/beside an _actual ocean_. 

This isn't difficult to find in 1.16.1 with Forge 32.0.90+. Perhaps the mod could limit fish spawning to levels near y=63 to limit this effect?

**Comment by CorgiTaco** [comment]
What biome mod are you using

**Comment by nepphhh** [comment]
This is with Biomes O Plenty. No other biome additions.

**Comment by CorgiTaco** [comment]
Fish spawns are controlled at a biome level so it could very well be bop since 1.16 did introduce a new fish spawn category. But again I'm not sure, take out bop and test it in only vanilla biomes.

**Comment by nepphhh** [comment]
Roger that, will do.
