### ISSUE TITLE
A few things ive noticed. 1.16 World gen issues.

### ISSUE THREAD

**Issue by Kinsypoo** [yungnickyoung/Better-Caves#65]
I am not sure how much of it is YUNGs and how much is other mods, but so far ive seen 
1. Floating grass/flowers on top of most caves. Things like surface water pools also do this for some reason.

2. things like rivers not properly generating near a cavern entrance for example
This river has spawned half on top of a ravine just kinda floating above it. 
![image](https://user-images.githubusercontent.com/69311631/89541852-e1370100-d7cc-11ea-9936-1fdc29497c68.png)

3. The YUNGs better mineshafts will spawn inside a flooded cave and just have floating water all around them. This one is literally just on the ocean floor lol. 
![image](https://user-images.githubusercontent.com/69311631/89541766-c9f81380-d7cc-11ea-94ef-b8e401735cdd.png)
![image](https://user-images.githubusercontent.com/69311631/89541943-00ce2980-d7cd-11ea-8f8c-3fcc7225efef.png)
Just lots of weird and broken world gen issues it seems like. Understandable since its a new version and all. Only other world gen effecting mods are quark and BOP if some of these issues are theirs sorry.

**Comment by yungnickyoung** [comment]
1. #51 
2. Ravines are generated using vanilla code, so this is actually just an issue with vanilla. It shouldn't occur often I don't think
3. yungnickyoung/YUNGs-Better-Mineshafts#12

All of these are referenced elsewhere, so I'm marking this as a duplicate and closing it
