### ISSUE TITLE
[1.16.2] Error Processing Deferred Work

### ISSUE THREAD

**Issue by Quearrel** [yungnickyoung/Better-Caves#68]
Everything loads fine, until I get this error; Yung's BetterCaves has encountered an error processing deferred work.
Here is the log;
[latest.log](https://github.com/yungnickyoung/YUNGs-Better-Caves/files/5134734/latest.log)
Using the version for minecraft 1.16.2

**Comment by yungnickyoung** [comment]
This probably happens due to other modders mistakenly making the carvers list into an immutable list to match the new behavior for the list of features in 1.16.2. I should be able to fix this soon.

**Comment by yungnickyoung** [comment]
Ok, so if those of you experiencing this issue could download the dev build JAR file from [here](https://github.com/yungnickyoung/YUNGs-Better-Caves/releases/tag/v1.16.2-1.0.1-dev) and let me know if it fixes anything

**Comment by yungnickyoung** [comment]
No response so I'm gonna assume it worked. Should be fixed in v1.16.2-1.0.1. Closing the issue.
