### ISSUE TITLE
Regarding the FAQ and Fabric

### ISSUE THREAD

**Issue by MechanosG** [yungnickyoung/Better-Caves#69]
Heya.  So, I take it you don't plan on making a Fabric version.  Which is fine, to each their own.  But I was just curious about your stance on it?  Since the FAQ is on Discord I'm unable to easily read it.  I ask because YUNG's Better Caves is pretty much my favorite mod overall, but after reading these:
https://gist.github.com/jellysquid3/629eb84a74ab326046faf971150dc6c3
https://gist.github.com/jellysquid3/8b68b81a5e48462f8690284a0a3c89a1

..it makes me feel like it's best if I just switch to Fabric, despite being a very long time Forge user.  I hope you understand, and I don't mean to bother you about Fabric related things.

**Comment by Lughbaloo** [comment]
F.A.Q.
Does this work with X mod?
All of my mods are widely supported and are likely to work with all other major mods. Feel free to ask in one of the support channels if you're experiencing issues.

Help! I'm lagging!
When using   YUNG's Better Caves, a small amount of lag is fairly normal for the first few minutes of worldgen if your PC isn't great.   YUNG's Better Caves shouldn't impact performance very significantly, so if you're lagging a lot, odds are it isn't this mod causing it. I also recommend getting a performance enhancing mod like Phosphor.

Do I need to make a new world? Are existing chunks affected?
Nope! Any new chunks loaded for the first time will use the caves and structures from my mods. Previously generated chunks are unaffected.

Can I use this in my modpack?
Absolutely! 

Does this work on a server? Can it be server-side only?
Yep!
For   YUNG's Better Mineshafts,   Save My Stronghold,   YUNG's Law, and   YUNG's Better Caves (1.12 only), clients won't need the mods installed - they won't even need Forge!

However, for   YUNG's Better Caves 1.14+ clients must also have the mod installed.

Does this work with Fabric?
There are no plans to support Fabric at this time. Please don't ask. The only Fabric port that exists is   YUNG's Better Mineshafts for 1.15.2, and it will not be supporting newer versions of Minecraft any time soon.

Will you support version X?
No. Other versions will not be supported, so please don't ask. Major future versions of MC will likely receive support.

Is this ABSOLUTELY GIGANTIC lava cavern / flat cave from your mod?
It's probably a mega cave or crevice from Quark.

**Comment by Enethim** [comment]
"Does this work with Fabric?
There are no plans to support Fabric at this time. Please don't ask."
Breaks my heart, all the cave mods for Fabric are wack.
This mod is only reason I'm still on forge.

**Comment by yungnickyoung** [comment]
Someone else is actually in the process of porting to Fabric. No promises it will happen, but there is a chance if the port turns out good.

I don't particularly care about all the Forge drama. I will support whichever platform has the most users.

**Comment by MechanosG** [comment]
Nice.  That's good to know, in both regards.  Thanks

**Comment by Enethim** [comment]
Fabric is gaining popularity, its a rising star, whole lot easier to make mods with, many experienced modders are shifting towards it and new modders just downright state they wont make any mods on forge, (Fabric runs faster and smoother) Also when "Sodium" will have shader support in near future that will end optifine's whole career (Compared to optifine Sodium has 10 times more performance gain) and in chain reaction to that Forge's career as well.

**Comment by Lughbaloo** [comment]
Github Issues isn't the place for political chatter regarding the two platforms. This post should be considered closed.
