### ISSUE TITLE
Feature Request: Option for global whitelist

### ISSUE THREAD

**Issue by yungnickyoung** [yungnickyoung/Better-Caves#7]
Add an option for global whitelist so that Better Caves spawn in every dimension (except Nether and End?)

**Comment by AllieWade** [comment]
I think this was addressed in #3 and added to a recent release of the mod. Does that look like what you were after?

**Comment by yungnickyoung** [comment]
Lol, I appreciate you helping out but I'm the mod author! I opened this (for my own organization and reminder) in response to a CF comment, to create an option for having Better Caves automatically be enabled on every dimension, rather than having to manually whitelist each dimension. Currently the process is manual for any additional dimensions.

**Comment by AllieWade** [comment]
Pfffffffffffffffffffffft. I can't even believe I missed that, lol. Sorry about that!

For what it's worth, I am _loving_ your mod.

**Comment by yungnickyoung** [comment]
Lol it's all good. Glad you're enjoying it :)

**Comment by yungnickyoung** [comment]
Added in 1.5.0
