### ISSUE TITLE
Obsidian/magma layer is still generated at y=11 in flooded caves even if the fluid below is water

### ISSUE THREAD

**Issue by muzikbike** [yungnickyoung/Better-Caves#72]
For the following cave, a layer of obsidian blocks and magma blocks is generated at y=10, implying that this cave hits a layer of lava typical of deep caves.
![2020-09-28_18 10 11](https://user-images.githubusercontent.com/52297970/94469783-94651a80-01be-11eb-9450-9ffcf86b52e1.png)

However, looking below this sheet of blocks reveals that the area below is actually flooded with water:
![2020-09-28_18 10 15](https://user-images.githubusercontent.com/52297970/94469823-a5ae2700-01be-11eb-9bce-41c9661bcecd.png)

Having this generate there doesn't really make much sense for water, so it'd be better if it just generated when a flooded cave hits lava, and those that hit water should just be continuous down to bedrock.
![2020-09-28_18 10 25](https://user-images.githubusercontent.com/52297970/94469967-db531000-01be-11eb-8609-b0f355bd9911.png)

**Comment by yungnickyoung** [comment]
Good catch.. I never really thought about that

**Comment by yungnickyoung** [comment]
Fixed with v1.1 in 1.16.4.

1.14 and 1.15 are no longer supported, and will therefore not be receiving this fix.
