### ISSUE TITLE
[1.15.2] Not a only server-side mod

### ISSUE THREAD

**Issue by Intezium** [yungnickyoung/Better-Caves#73]
Forge-31.2.41
BetterCaves-1.0
This prevent joining the server.
![](https://user-images.githubusercontent.com/20191322/94384652-c8ebbe80-014b-11eb-967c-4388b17f0691.png)

**Comment by yungnickyoung** [comment]
This is known behavior. It's necessary due to internal changes in Minecraft starting in 1.13
