### ISSUE TITLE
[1.16.3] Better Cave's ravines cause floating grass in the air

### ISSUE THREAD

**Issue by BugmanBugman** [yungnickyoung/Better-Caves#78]
![2020-10-14_14 38 23](https://user-images.githubusercontent.com/40730042/96071741-5cb9cc00-0e68-11eb-8bdb-04c54ed2ea6e.png)
![2020-10-14_14 38 26](https://user-images.githubusercontent.com/40730042/96071745-5deaf900-0e68-11eb-8336-bca14400bc3a.png)
![2020-10-13_21 13 36](https://user-images.githubusercontent.com/40730042/96071749-60e5e980-0e68-11eb-9156-3830d01d2913.png)

**Comment by yungnickyoung** [comment]
Duplicate of #51
