### ISSUE TITLE
Caves carve through bedrock 

### ISSUE THREAD

**Issue by tomfulghum** [yungnickyoung/Better-Caves#8]
Caves and caverns seem to carve through bedrock (except the lowest layer) if the bedrock layers setting is larger than 1 and flatten bedrock is set to false. This is a very minor issue, but i personally prefer my bedrock layers to not be flat.

Pictures:
![2019-10-04_20 57 08](https://user-images.githubusercontent.com/5806810/66233782-6d2f5680-e6ec-11e9-9248-33d950a0feb1.png)
![2019-10-04_21 15 00](https://user-images.githubusercontent.com/5806810/66233783-6d2f5680-e6ec-11e9-997b-5e3c9ba01220.png)
![2019-10-04_21 15 49](https://user-images.githubusercontent.com/5806810/66233784-6d2f5680-e6ec-11e9-8bfe-d8fc78130cb3.png)

**Comment by yungnickyoung** [comment]
Thanks for pointing this out. The bedrock flattening/mining in Better Caves admittedly received minimal testing. I'll be sure to take a look.

**Comment by yungnickyoung** [comment]
This will be fixed in the next release, v1.12.2-1.5.1

Btw, just wanted to point out that the Bedrock Layer Width setting doesn't actually do anything if Flatten Bedrock is disabled.
