### ISSUE TITLE
YUNG's better caves(better caves) encountered an error during the load registries phase.

### ISSUE THREAD

**Issue by moosyman** [yungnickyoung/Better-Caves#82]
Honestly, I don't know what went wrong, but im on 1.16.3. Anyways, here's the crash report.
https://pastebin.com/GWbfFLxz

**Comment by yungnickyoung** [comment]
Please try updating to the latest version of Forge.

**Comment by BugmanBugman** [comment]
https://hatebin.com/jemqmhtypm
This and better mineshafts still seem to crash on Forge 34.1.32

**Comment by yungnickyoung** [comment]
Must be something with the newer versions of Forge then? Try using the recommended version. I'll look into it.

**Comment by moosyman** [comment]
> Please try updating to the latest recommended version of Forge.

Im actually on the latest, but alright. Ill check the recommended version and see if that helps. I've actually been trying to get a few 1.16.3 mods running and it wasn't just this mod giving me this issue, but I was able to single it out as one of them. I think its just that the latest forge version is buggy.

**Comment by JeffersonDoan** [comment]
Just tried with Forge 34.1.33 (just released, mentioned in a [Quark issue](https://github.com/Vazkii/Quark/issues/2618#issuecomment-717346449)) that said it should be compatible with all 1.16.3 mods but Better Caves and Mineshafts still crash on startup.

Further details:
Forge: 34.1.33
Better Caves: 1.16.2-1.0.3
(Better Mineshafts: 1.16.2-1.0)

[Crash Report](https://pastebin.com/GR0479Hy)
[latest.log](https://pastebin.com/PszY232n)
[debug.log](https://pastebin.com/rA8KZw8P)

**Comment by TheCurle** [comment]
This is a different issue. 
Registry.register is unsupported and always has been. This mod is using those functions and causing an error.
https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/blob/forge-1.16/src/main/java/com/yungnickyoung/minecraft/bettermineshafts/init/ModStructures.java#L79

I will create a bug report there.

**Comment by TheCurle** [comment]
I've submitted the bug report to [the Better Mineshafts repo](https://github.com/yungnickyoung/YUNGs-Better-Mineshafts/issues/25). It looks like there's a similar issue present in Better Caves, and i will do the same here.

**Comment by yungnickyoung** [comment]
Forge locked the `Registry.register` methods, so now all modders have to register using the Forge functions. Fix will be out later today.
