### ISSUE TITLE
MC 1.16.3 Fabric Caves Destroying Stronghold

### ISSUE THREAD

**Issue by javenjefven** [yungnickyoung/Better-Caves#84]
I know this is something that can happen in vanilla MC, but it seems to happen almost 100% of the time with the mod enabled, a lot of the time throwing the stronghold across multiple caves in 10s of y levels in a ravine . Is there some way to Whitelist all Strongholds, or the chunk that they inhabit?

**Comment by yungnickyoung** [comment]
This is part of vanilla behavior. It's the reason I made Save My Stronghold, which unfortunately isn't available for Fabric.
