### ISSUE TITLE
[1.15.2] Better Caves breaks "Cavern: Miner"'s Huge Cavern dimension

### ISSUE THREAD

**Issue by gamax92** [yungnickyoung/Better-Caves#85]
Minecraft 1.15.2
Forge 31.2.45
Better Caves 1.0
Cavern: Miner 3.0.6
https://www.curseforge.com/minecraft/mc-mods/cavern-miner

When Better Caves is installed, the Huge Cavern dimension from Cavern: Miner has random broken chunks.
Even more confusing, Better Caves' config is set to only affect the Overworld by default, so I don't understand why it would be affecting other dimensions.

The Huge Cavern can be accessed by making a nether portal shape out of mossy cobblestone and right clicking with a diamond instead of flint and steel.

Broken Generation:
![2020-11-04_22 00 15](https://user-images.githubusercontent.com/815145/98200571-1d245400-1eeb-11eb-9913-3becfbb9306e.png)

Correct Generation (Ignore missing portal):
![2020-11-04_22 02 32](https://user-images.githubusercontent.com/815145/98200595-29101600-1eeb-11eb-8050-d98a598fac28.png)

**Comment by yungnickyoung** [comment]
Apologies, but due to time constraints 1.15 is no longer supported. I will only be actively supporting 1.12 and 1.16 for now.
