### ISSUE TITLE
Gigantic lava lake spawned underneath huge water lake at bedrock and crashes world

### ISSUE THREAD

**Issue by lizamartinez** [yungnickyoung/Better-Caves#86]
Chunk: (at 10,0,4 in 17,53; contains blocks 272,0,848 to 287,255,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)

Unplayable world gen because huge lava lake spawned underneath huge water lake. Server tries to make obsidian but it overloads server and corrupts lava blocks. Used on forge server. Version 1.16.3.

**Comment by yungnickyoung** [comment]
Are you using Quark?

**Comment by lizamartinez** [comment]
> Are you using Quark?

yes

**Comment by yungnickyoung** [comment]
The giant lava lake is probably a Quark mega cavern. They're known for having bad placement. I would disable those, as there isn't really anything I can do about it on my end.

**Comment by lizamartinez** [comment]
> The giant lava lake is probably a Quark mega cavern. They're known for having bad placement. I would disable those, as there isn't really anything I can do about it on my end.

okay! thank you for such a quick response!
