### ISSUE TITLE
[1.16.4] Some funky lava generation I noticed

### ISSUE THREAD

**Issue by MoreKerosine** [yungnickyoung/Better-Caves#90]
Attached is a photo. I was messing around in spectator mode when I noticed this
![2020-11-13_17 51 20](https://user-images.githubusercontent.com/71890236/99128561-25f6e300-25d9-11eb-81a1-a2f46ea0d563.png)

**Comment by yungnickyoung** [comment]
Looks like a vanilla lava lake. Stuff like this is a side effect of having to implement my carver as a feature. Unfortunately there isn't anything I can do about it. Sorry!
