### ISSUE TITLE
Ice and Fire Issue

### ISSUE THREAD

**Issue by traxonLp** [yungnickyoung/Better-Caves#91]
Hi, first things first. Nice mod. The Caves looks insane.
But if i install Ice and fire too, threre aren't any dragon nests.
I think Better-Caves overrides it. But i don't know. Any solutions?

**Comment by CorgiTaco** [comment]
Their latest version on CurseForge currently has no world gen working and dragons do not spawn, so this isn't a BC issue.

**Comment by yungnickyoung** [comment]
I'm assuming this is for 1.16.3?
