### ISSUE TITLE
(fabric) Lava generation issue in nether caves

### ISSUE THREAD

**Issue by SylisMC** [yungnickyoung/Better-Caves#94]
Lava floats in caves when generating in the nether. 
Fabric 0.6.1.51 (MC 1.16.4)

![2020-11-29_22 23 25](https://user-images.githubusercontent.com/19602662/100565488-c31c7180-3291-11eb-8c4b-298ce5b1fd2d.png)

**Comment by yungnickyoung** [comment]
This is expected behavior. Please try the [Nether preset](https://github.com/yungnickyoung/YUNGs-Better-Caves/tree/fabric-1.16/presets/default-with-nether), which will automatically fill all caves below y=30 with lava (matching the rest of the Nether).
