### ISSUE TITLE
lava gen weirdness

### ISSUE THREAD

**Issue by superon** [yungnickyoung/Better-Caves#98]
hi i have "generateLocalWaterLevels" false in the cave biomes config but is there something i should be doing about the funky lava?

https://imgur.com/bJDetKg

https://imgur.com/J0j5bVI

**Comment by yungnickyoung** [comment]
This may just be a compat issue with vanilla lakes (they have pretty shitty placement). Please provide your version of BC and Cave Biomes

**Comment by superon** [comment]
sorry yea BetterCaves-fabric-1.16.2-1.0.3 & cavebiomes-0.5.1

**Comment by yungnickyoung** [comment]
This is potentially a result of my carver being implemented as a feature. This has been fixed for Forge versions as of Better Caves v1.1 for 1.16. I'm unsure if I'll be porting this update to Fabric. I'll leave this issue open just in case I do.

**Comment by Matiss-Priednieks** [comment]
Heyo! I've a similar issue but it's in relation to do with water lakes and rivers near bedrock where water and lava source blocks don't spread out and there are air gaps all over the place. I've the Biomes You'll go mod installed as well and have a feeling this might be an issue? EDIT: Not sure if I should make my own ticket or no

**Comment by yungnickyoung** [comment]
@Marineti-Gurki please make a separate issue, with more details (e.g. version information and pictures)

**Comment by yungnickyoung** [comment]
Should be fixed in v1.1.
